name: 'TestInfra Action'
description: 'GitHub Action running your TestInfra tests'
branding:
  icon: 'sliders'
  color: 'orange'
inputs:
  image:
    description: The Docker image to test
    required: true
  testsPath:
    description: The path that contains the Infra tests
    required: false
    default: 'test'
  cmd:
    description: Command to run on container start
    required: false
    default: ''
  flags:
    description: Additional flags to pass to docker run aside --rm, -t, and -d
    required: false
    default: ''
  testSuite:
    description: Specify a specific test suite to run
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: Checkout 🐙
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        repository: 'WyriHaximus/github-action-testinfra'
        ref: 'main'
        path: .wyrihaximus-test-infra-action
        sparse-checkout-cone-mode: false
        sparse-checkout: |
          test.sh
    - name: Checkout 🛒
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        path: .wyrihaximus-test-infra-tests
        sparse-checkout-cone-mode: false
        sparse-checkout: |
          ${{ inputs.testsPath }}
    - name: Run Infra Tests 🏗️
      shell: bash
      run: echo "${{ inputs.image }}" | tr ',' '\n' | xargs -I % ./.wyrihaximus-test-infra-action/test.sh "%" "./.wyrihaximus-test-infra-tests/${{ inputs.testsPath }}" "${{ inputs.cmd }}" "${{ inputs.flags }}" "${{ matrix.testSuite }}"
